name: musso_deme_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.9.1
  just_audio: ^0.9.42
  provider: ^6.0.5
  font_awesome_flutter: ^10.12.0
  http: ^0.13.6
  # Synthèse vocale pour l’accueil audio
  flutter_tts: ^4.0.2
  # Using speech_to_text instead of vosk_flutter due to build issues
  permission_handler: ^11.3.1
  
  # Reconnaissance vocale online (si tu veux laisser les 2)
  speech_to_text: ^7.0.0

  image_picker: ^1.2.1
  flutter_svg: ^2.0.9
  shared_preferences: ^2.5.3
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audios/